"""
This is a setup.py script generated by py2applet

Usage:
    python3.6 setup.py py2app -A
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('ui',['ui/error.ui','ui/main.ui','ui/warning.png']),
    'forwader.py',
    'globalVariables.py',
    'connectionThread.py',
    ]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
